apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: api-gateway
  namespace: default
spec:
  maxReplicas: 4
  minReplicas: 1
  scaleTargetRef:
    kind: Deployment
    name: api-gateway
    apiVersion: apps/v1
  targetCPUUtilizationPercentage: 400
