kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: new-joiner
rules:
  - apiGroups: ["", "apps", "autoscaling", "extensions"]
    resources: ["*"]
    verbs:
      - get
      - list
      - watch
---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: put-specific-user-into-new-joiner-role
subjects:
  - kind: ClusterRole
    name: francis-linux-login-name
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: new-joiner
